// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm_nO4qqUvB3bsvsV4McrVcy026bUfxr8',
    appId: '1:513283139484:web:052b0988a6701dd8234a59',
    messagingSenderId: '513283139484',
    projectId: 'wisdom-waves-by-nitin',
    authDomain: 'wisdom-waves-by-nitin.firebaseapp.com',
    storageBucket: 'wisdom-waves-by-nitin.firebasestorage.app',
    measurementId: 'G-53FENDRCW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCohEPd27x9bOQFnSntjo3PUlQ3wtjEheM',
    appId: '1:513283139484:android:f6dbe47aa892b59b234a59',
    messagingSenderId: '513283139484',
    projectId: 'wisdom-waves-by-nitin',
    storageBucket: 'wisdom-waves-by-nitin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8yoSiIVt2pnqnbYRg_eCv_Mz83MWO8kY',
    appId: '1:513283139484:ios:7ce06144ef8c779f234a59',
    messagingSenderId: '513283139484',
    projectId: 'wisdom-waves-by-nitin',
    storageBucket: 'wisdom-waves-by-nitin.firebasestorage.app',
    iosBundleId: 'com.example.wisdomWavesByNitin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8yoSiIVt2pnqnbYRg_eCv_Mz83MWO8kY',
    appId: '1:513283139484:ios:7ce06144ef8c779f234a59',
    messagingSenderId: '513283139484',
    projectId: 'wisdom-waves-by-nitin',
    storageBucket: 'wisdom-waves-by-nitin.firebasestorage.app',
    iosBundleId: 'com.example.wisdomWavesByNitin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm_nO4qqUvB3bsvsV4McrVcy026bUfxr8',
    appId: '1:513283139484:web:32eaa40a09986b32234a59',
    messagingSenderId: '513283139484',
    projectId: 'wisdom-waves-by-nitin',
    authDomain: 'wisdom-waves-by-nitin.firebaseapp.com',
    storageBucket: 'wisdom-waves-by-nitin.firebasestorage.app',
    measurementId: 'G-LJ927L18F7',
  );
}
